### ISSUE TITLE
Led ui control throws exception when used

### ISSUE THREAD

**Issue by nikotanghe** [Adorkable/node-red-contrib-ui-led#74]
Installation from within node-red ui, created a led ui node with default properties.
Node-red is installed with apt-get.
When running the dashboard, no control is generated.

Logs ->

24 Feb 19:52:40 - [info] Installed module: node-red-contrib-ui-led
24 Feb 19:52:40 - [info] Added node types:
24 Feb 19:52:40 - [info]  - node-red-contrib-ui-led:ui_led
24 Feb 19:53:33 - [info] Stopping modified nodes
24 Feb 19:53:33 - [info] Stopped modified nodes
24 Feb 19:53:33 - [info] Starting modified nodes
Error: Cannot find module 'node-red-dashboard'
    at Object.requireModule [as require] (/usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/util.js:48:19)
    at new LEDNodeConstructor (/home/ntanghe/.node-red/node_modules/node-red-contrib-ui-led/dist/nodes/ui_led/ui_led.js:9:42)
    at Object.createNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:493:31)
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:193:48)
    at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:345:33)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:212:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND'
}
TypeError: Cannot read property 'padEnd' of undefined
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:241:62)
    at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:345:33)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:212:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
24 Feb 19:53:33 - [info] Started modified nodes

**Comment by yoiang** [comment]
Very strange, it can't find **node-red-dashboard**? Is there anything unique about your installation that comes to mind?

**Comment by nikotanghe** [comment]
> Very strange, it can't find **node-red-dashboard**? Is there anything unique about your installation that comes to mind?

nope, apt-get on debian linux 9, no customizations, everything installed en configured from the node-red interface.
Anything specific that I should check ?
