### ISSUE TITLE
I am seeing this when NR is starting.

### ISSUE THREAD

**Issue by Just-another-pleb** [Adorkable/node-red-contrib-ui-led#75]
I have version
0.4.8

But I am not sure it is important.

```
TypeError: Cannot read property 'config' of null
    at addWidget (/home/me/.node-red/node_modules/node-red-dashboard/index.js:73:39)
    at Object.addWidget (/home/me/.node-red/node_modules/node-red-dashboard/index.js:137:48)
    at new LEDNodeConstructor (/home/me/.node-red/node_modules/node-red-contrib-ui-led/dist/nodes/ui_led/ui_led.js:30:29)
    at Object.createNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/util.js:493:31)
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:194:48)
    at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:345:33)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:210:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Sorry if it has been fixed with 0.4.9

Thanks in advance.

Just updated the dashboard and your node to the latest.   
Still happening.

**Comment by yoiang** [comment]
Hey @Just-another-pleb is this the same as #60?

**Comment by Just-another-pleb** [comment]
Oh dear, sorry.

I trip on this as I don't often do restarts of Node-red.

It is just all things are up to date (latest versions) and my assumption is that it shouldn't give an *error* if all is good.

Sorry - really.   My memory is really not as good as it used to be.
If you want, you can close this.
I don't want to - only because as much as it is like #60, I am not sure if this now supersede it.
