### ISSUE TITLE
LED node does not handle being in a disabled group - Cannot read property config of null

### ISSUE THREAD

**Issue by colinl** [Adorkable/node-red-contrib-ui-led#80]
If the group containing the LED node is disabled then, on deploy, this is seen in the log
```
TypeError: Cannot read property 'config' of null
    at new LEDNodeConstructor (/home/colinl/.node-red/node_modules/node-red-contrib-ui-led/dist/nodes/ui_led/ui_led.js:25:44)
    at Object.createNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/util.js:86:27)
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:205:48)
    at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:371:33)
```

**To Reproduce**

1. Add an LED node
2. Disable the group
3. Deploy, watching the log

**Versions**

- node-red-contrib-ui-led: 0.4.9
- node-red: 1.3.5
- node-red-dashboard: 2.29.1

**Platform**

- OS: Ubuntu
- Browser: Firefox
- Version 89.0.1

**Comment by colinl** [comment]
In fact this was a dashboard issue, it has been fixed in node-red-dashboard@2.30.0

**Comment by yoiang** [comment]
@colinl Sorry for not responding, thank you for following up!

**Comment by colinl** [comment]
No problem, thanks for providing the node in the first place.
