### ISSUE TITLE
Error installing from palette, dependency error

### ISSUE THREAD

**Issue by randomhammer** [Adorkable/node-red-contrib-ui-led#84]
I'm sorry if this was addressed elsewhere, but I was unable to find a reference. I am trying to install from my Node RED instance using Manage Palette menu choice. I am getting an incomprehensible (to me at least, I am not good at deciphering Node errors) message about dependency issues. I have dashboard version 3.0.4 running just fine, and all of the built-in widgets I've tried work fine. When I try to install the LED widget I get this: 

```
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--no-audit',
0 verbose cli   '--no-update-notifier',
0 verbose cli   '--no-fund',
0 verbose cli   '--save',
0 verbose cli   '--save-prefix=~',
0 verbose cli   '--production',
0 verbose cli   '--engine-strict',
0 verbose cli   'node-red-contrib-ui-led@0.4.9'
0 verbose cli ]
1 info using npm@7.5.2
2 info using node@v12.22.5
3 timing config:load:defaults Completed in 5ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 6ms
5 timing config:load:builtin Completed in 6ms
6 timing config:load:cli Completed in 10ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/opt/nodered/.node-red/.npmrc Completed in 1ms
9 timing config:load:project Completed in 3ms
10 timing config:load:file:/opt/nodered/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 2ms
17 timing config:load:setEnvs Completed in 3ms
18 timing config:load Completed in 34ms
19 verbose npm-session 86e657c9528e0445
20 timing npm:load Completed in 61ms
21 timing arborist:ctor Completed in 3ms
22 timing idealTree:init Completed in 221ms
23 timing idealTree:userRequests Completed in 5ms
24 silly idealTree buildDeps
25 silly fetch manifest node-red-contrib-ui-led@0.4.9
26 timing arborist:ctor Completed in 0ms
...skipping...
27 http fetch GET 304 https://registry.npmjs.org/node-red-contrib-ui-led 950ms (from cache)
28 silly fetch manifest node-red-dashboard@~3.0.4
29 http fetch GET 304 https://registry.npmjs.org/node-red-dashboard 485ms (from cache)
30 silly fetch manifest node-red-dashboard@^2.23.3
31 timing idealTree Completed in 1743ms
32 timing command:install Completed in 1764ms
33 verbose stack Error: unable to resolve dependency tree
33 verbose stack     at Arborist.[failPeerConflict] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1115:25)
33 verbose stack     at Arborist.[loadPeerSet] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1095:34)
33 verbose stack     at async Arborist.[buildDepStep] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:824:11)
33 verbose stack     at async Arborist.buildIdealTree (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
33 verbose stack     at async Promise.all (index 1)
33 verbose stack     at async Arborist.reify (/usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:127:5)
33 verbose stack     at async install (/usr/share/nodejs/npm/lib/install.js:38:3)
34 verbose cwd /opt/nodered/.node-red
35 verbose Linux 5.10.60-v8+
36 verbose argv "/usr/bin/node" "/bin/npm" "install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix=~" "--production" "--engine-strict" "node-red-contrib-ui-led@0.4.9"
37 verbose node v12.22.5
38 verbose npm  v7.5.2
39 error code ERESOLVE
40 error ERESOLVE unable to resolve dependency tree
41 error
42 error While resolving: node-red-project@0.0.1
42 error Found: node-red-dashboard@3.0.4
42 error node_modules/node-red-dashboard
42 error   node-red-dashboard@"~3.0.4" from the root project
42 error
42 error Could not resolve dependency:
42 error peer node-red-dashboard@"^2.23.3" from node-red-contrib-ui-led@0.4.9
42 error node_modules/node-red-contrib-ui-led
42 error   node-red-contrib-ui-led@"0.4.9" from the root project
42 error
42 error Fix the upstream dependency conflict, or retry
42 error this command with --force, or --legacy-peer-deps
42 error to accept an incorrect (and potentially broken) dependency resolution.
42 error
42 error See /opt/nodered/.npm/eresolve-report.txt for a full report.
43 verbose exit 1
```

This is running on a Raspberry Pi 4 running DietPi with the following result from `name -a`

`Linux tesla 5.10.60-v8+ #1449 SMP PREEMPT Wed Aug 25 15:01:33 BST 2021 aarch64 GNU/Linux`

Node-Red was installed in a private folder, and not as a global module. 

Apart from this being the absolute worst error format I've ever seen from a language I have no idea how to interpret this. Is the problem that I need version 2.23.3 of the dashboard? Or a different version of of the LED widget? Is installing from the palette not supported and I missed that somewhere? Any help would be appreciated.

**Comment by randomhammer** [comment]
I just ran installed from the command line using 2pm and the widget installed correctly. This appears to be related to installing from the palette. Closing due to finding a workaround.
